import { writeFile } from 'node:fs/promises';
import { relative, join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Ajv2020, _ } from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { OPENRESULT_1_0_SCHEMA } from '../../sdk/js/packages/validate/src/schema.generated.js';

/**
 * Compile the schema once, here, instead of in every consumer at runtime.
 *
 * `ajv.compile()` builds its validator with `new Function`, which a page under
 * a Content Security Policy without `'unsafe-eval'` is not allowed to do. That
 * is not an exotic configuration — it is the policy any site displaying
 * documents from strangers should have, and openresult.dev is one of them. The
 * choice was to weaken the policy or to stop generating code at runtime.
 *
 * Precompiling also drops Ajv itself out of the browser bundle, and removes the
 * first-validation pause.
 */

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const TARGET = join(repoRoot, 'sdk/js/packages/validate/src/schema.validator.generated.js');

const ajv = new Ajv2020({
  allErrors: true,
  strict: false,
  verbose: true,
  // Without this, Ajv emits `require("ajv-formats/dist/formats")` inside an ESM
  // module, which no browser can resolve. Naming the identifier here lets the
  // import be written properly at the top of the file.
  code: { source: true, esm: true, formats: _`formats` },
});
addFormats.default(ajv);

const validate = ajv.compile(OPENRESULT_1_0_SCHEMA);
const source = standaloneCode
  .default(ajv, validate)
  // Ajv reaches for its own length helper the same way. It is a CommonJS
  // module whose function hangs off `.default`, so the import below unwraps it
  // rather than naming the module object — which is a function of nothing and
  // fails only when a document actually has a string to measure.
  .replaceAll('require("ajv/dist/runtime/ucs2length").default', 'ucs2length');

const imports =
  `import { fullFormats as formats } from 'ajv-formats/dist/formats.js';\n` +
  `import ucs2lengthModule from 'ajv/dist/runtime/ucs2length.js';\n` +
  `const ucs2length = ucs2lengthModule.default ?? ucs2lengthModule;\n`;

await writeFile(
  TARGET,
  `// Generated by tools/generate/validator.ts from schema/openresult-1.0.schema.json.\n` +
    `// Do not edit. Run \`pnpm generate:schema\` after changing the schema.\n` +
    `/* eslint-disable */\n` +
    `${imports}${source}`,
  'utf8',
);

console.log(`Wrote ${relative(process.cwd(), TARGET)} (${Math.round(source.length / 1024)} kB)`);
